function net = train_column(train_imds,test_imds,layers)
%TRAIN_SHAPE_COLUMN Train a column of the mc-cnn
%   Detailed explanation goes here
%   net = train_column(imds,layers)
    options = trainingOptions('sgdm', ...
    'InitialLearnRate',0.01, ...
    'MaxEpochs',10, ...
    'Shuffle','every-epoch', ...
    'ValidationFrequency',15, ...
    'ValidationData',test_imds, ...
    'Verbose',false, ...
    'Plots','training-progress');
    
    net = trainNetwork(train_imds, layers, options);
end

