function net = train_column(train_imds,layers)
%TRAIN_COLUMN Train a column of the mc-cnn.
%   
%   net = TRAIN_COLUMN(train_imds,layers) Train a column,
%   described by layers, of the mc-cnn. This routine centralizes the
%   trainingOptions. train_imds is the imds used for training.
%
%   See also trainNetwork, trainingOptions

    options = trainingOptions('sgdm', ...
    'LearnRateSchedule','piecewise', ...
    'InitialLearnRate',0.0003,...
    'LearnRateDropFactor',0.5,...
    'LearnRateDropPeriod',10,...
    'MaxEpochs',30, ...
    'MiniBatchSize',256, ...
    'Shuffle','every-epoch',...
    'Verbose',true,...
    'VerboseFrequency',1,...
    'ExecutionEnvironment', 'parallel',...
    'DispatchInBackground', true);
    %   'Plots','training-progress'
    %   'ValidationFrequency',4
    %   'ValidationData',test_imds
    %   'ExecutionEnvironment', 'parallel'
    %   'DispatchInBackground', true
    
    net = trainNetwork(train_imds, layers, options);
end

